- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 3h # Harmony: 1h -> 3h
    # Harmony start
    # - !type:RoleTimeRequirement
    #   role: JobDetective
    #   time: 3600 #1 hr, knowing how to use the tools is important
    # - !type:RoleTimeRequirement
    #   role: JobSecurityOfficer
    #   time: 18000 #5 hrs
    # Harmony end
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h
    - !type:OverallPlaytimeRequirement
      time: 12h # Harmony: 10h -> 12h
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponDisabler
  storage:
    back:
    - Flash
    - MagazinePistol
#   - WeaponPistolMk58 # Harmony - moved to loadouts

- type: chameleonOutfit
  id: HeadOfSecurityChameleonOutfit
  job: HeadOfSecurity
  hasMindShield: true
  equipment:
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckCloakHos
