- type: antag
  id: ListeningPost
  name: roles-antag-listening-post-name
  antagonist: true
  objective: roles-antag-listening-post-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 # 10 hours
