- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Convex
  #- Core
  - Elkridge
  - Fland
  #- Gate
  #- Loop # Harmony, removed
  - Marathon
  #- Meta # Harmony, removed
  - Oasis
  - Omega
  - Packed
  - Plasma
  - Reach
  #- Train
  # Harmony
  - Aspid
  - Barratry
  - Atlas
  - Mira