- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBloodBrother
  name: Blood Brother Role
  components:
  - type: BloodBrotherRole
  - type: MindRole
    antagPrototype: BloodBrother
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-blood-brother

- type: entity
  parent: MindRoleNukeops
  id: MindRoleNukeopsSapper
  name: Nukeops Sapper Role
  components:
  - type: MindRole
    antagPrototype: NukeopsSapper
