- type: mapModification
  id: MetaPermaPrisoner
  applyOn:
  - Meta
  additions:
  - prototype: SpawnPointPermaPrisoner
    position: -7.5, 55.5
  - prototype: SpawnPointPermaPrisoner
    position: -3.5, 55.5
  - prototype: SpawnPointPermaPrisoner
    position: 0.5, 55.5
